In [2]:
from sklearn import datasets
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
from sklearn.model_selection import train_test_split 
import pandas as pd


#iris 데이터 불러오기
iris = datasets.load_iris()

iris_data = iris.data # 아이리스 데이터를 넘파이 배열로 변환

iris_label = iris.target # 아이리스 데이터 라벨을 넘파이 배열로 변환

iris_df = pd.DataFrame(data=iris_data, columns = iris.feature_names) # 배열만들기
iris_df["label"] = iris.target

X_train, X_test, y_train, y_test = train_test_split(iris_data,
iris_label, random_state=7)
print('X_train 개수: ', len(X_train),', X_test 개수: ', len(X_test))

kn = KNeighborsClassifier()

kn.fit(X_train, y_train)
kn.score(X_test, y_test)


X_train 개수:  112 , X_test 개수:  38


0.8947368421052632

# Lab 1.
X_new = np.array([[7,2.1,6.9,0.3]])   
Sklearn의 KNeighborsClassifier 라이브러리 적용하여 예측하는 프로그램 작성하기

In [3]:
X_new = np.array([[7,2.1,6.9,0.3]])

name = kn.predict(X_new)

print("X_new의 꽃 이름은 :", iris.target_names[name]) # 꽃 이름이 무엇인지 까지 출력

X_new의 꽃 이름은 : ['virginica']


# Lab 2.
앞에서 분할된 테스트 데이터 38개의 품종예측 결과는 오른쪽과 같이 나타난다.    
이러한 형태의 출력을 보이도록 코드를 작성하시오.

In [4]:
name = kn.predict(X_test)

for i in range(len(name)):
  name_f = iris.target_names[name[i]]
  print(f"{X_test[i]} : {name_f}")

[5.9 3.  5.1 1.8] : virginica
[5.4 3.  4.5 1.5] : versicolor
[5.  3.5 1.3 0.3] : setosa
[5.6 3.  4.5 1.5] : versicolor
[4.9 2.5 4.5 1.7] : versicolor
[4.5 2.3 1.3 0.3] : setosa
[6.9 3.1 4.9 1.5] : versicolor
[5.6 2.7 4.2 1.3] : versicolor
[4.8 3.4 1.6 0.2] : setosa
[6.4 3.2 4.5 1.5] : versicolor
[6.7 3.  5.  1.7] : virginica
[6.  3.4 4.5 1.6] : versicolor
[5.2 4.1 1.5 0.1] : setosa
[7.2 3.6 6.1 2.5] : virginica
[5.2 3.4 1.4 0.2] : setosa
[5.9 3.2 4.8 1.8] : versicolor
[6.7 2.5 5.8 1.8] : virginica
[6.4 3.1 5.5 1.8] : virginica
[5.1 3.8 1.6 0.2] : setosa
[4.9 3.6 1.4 0.1] : setosa
[5.8 2.7 3.9 1.2] : versicolor
[6.9 3.2 5.7 2.3] : virginica
[6.1 2.9 4.7 1.4] : versicolor
[6.  2.2 5.  1.5] : versicolor
[7.2 3.  5.8 1.6] : virginica
[6.  3.  4.8 1.8] : versicolor
[6.2 2.9 4.3 1.3] : versicolor
[5.5 2.4 3.8 1.1] : versicolor
[5.8 2.7 5.1 1.9] : virginica
[6.7 3.1 5.6 2.4] : virginica
[6.2 2.8 4.8 1.8] : virginica
[5.7 2.6 3.5 1. ] : versicolor
[4.6 3.6 1.  0.2] : setosa
[6.9 3.1 5.4 2.1] :