In [2]:
from sklearn import datasets
import matplotlib.pyplot as plt

#iris 데이터 불러오기
iris = datasets.load_iris()

print(dir(iris)) # dir() 함수로 해당 객체의 변수와 메소드 확인

['DESCR', 'data', 'data_module', 'feature_names', 'filename', 'frame', 'target', 'target_names']


In [3]:
iris_data = iris.data # 아이리스 데이터를 넘파이 배열로 변환
print(iris_data.shape)

(150, 4)


In [4]:
iris_label = iris.target # 아이리스 데이터 라벨을 넘파이 배열로 변환
print(iris_label)
type(iris_label)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


numpy.ndarray

In [ ]:
iris.data

In [6]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
print(iris_df)

In [9]:
import pandas as pd
iris_df = pd.DataFrame(data=iris_data, columns = iris.feature_names) # 배열만들기
iris_df["label"] = iris.target

from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(iris_data,
iris_label, random_state=7)
print('X_train 개수: ', len(X_train),', X_test 개수: ', len(X_test))


X_train 개수:  112 , X_test 개수:  38


In [10]:
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

kn = KNeighborsClassifier()

kn.fit(X_train, y_train)
kn.score(X_test, y_test)


0.8947368421052632

In [11]:
X_new = np.array([[7,2.1,6.9,0.3]])

name = kn.predict(X_new)

print("X_new의 꽃 이름은 :", iris.target_names[name]) # 꽃 이름이 무엇인지 까지 출력

X_new의 꽃 이름은 : ['virginica']


In [ ]:
name = kn.predict(X_test)

print(name)

for i in range(len(name)):
  name_f = iris.target_names[name[i]]
  print(name_f)

In [31]:
name = kn.predict(X_test)

for i in range(len(name)):
  name_f = iris.target_names[name[i]]
  print(f"{X_test[i]} : {name_f}")

[5.9 3.  5.1 1.8] : virginica
[5.4 3.  4.5 1.5] : versicolor
[5.  3.5 1.3 0.3] : setosa
[5.6 3.  4.5 1.5] : versicolor
[4.9 2.5 4.5 1.7] : versicolor
[4.5 2.3 1.3 0.3] : setosa
[6.9 3.1 4.9 1.5] : versicolor
[5.6 2.7 4.2 1.3] : versicolor
[4.8 3.4 1.6 0.2] : setosa
[6.4 3.2 4.5 1.5] : versicolor
[6.7 3.  5.  1.7] : virginica
[6.  3.4 4.5 1.6] : versicolor
[5.2 4.1 1.5 0.1] : setosa
[7.2 3.6 6.1 2.5] : virginica
[5.2 3.4 1.4 0.2] : setosa
[5.9 3.2 4.8 1.8] : versicolor
[6.7 2.5 5.8 1.8] : virginica
[6.4 3.1 5.5 1.8] : virginica
[5.1 3.8 1.6 0.2] : setosa
[4.9 3.6 1.4 0.1] : setosa
[5.8 2.7 3.9 1.2] : versicolor
[6.9 3.2 5.7 2.3] : virginica
[6.1 2.9 4.7 1.4] : versicolor
[6.  2.2 5.  1.5] : versicolor
[7.2 3.  5.8 1.6] : virginica
[6.  3.  4.8 1.8] : versicolor
[6.2 2.9 4.3 1.3] : versicolor
[5.5 2.4 3.8 1.1] : versicolor
[5.8 2.7 5.1 1.9] : virginica
[6.7 3.1 5.6 2.4] : virginica
[6.2 2.8 4.8 1.8] : virginica
[5.7 2.6 3.5 1. ] : versicolor
[4.6 3.6 1.  0.2] : setosa
[6.9 3.1 5.4 2.1] :

In [ ]:
import matplotlib.pyplot as plt

kn.fit(X_train, y_train)
kn.score(X_test, y_test)

#표준 점수로 바꾸기
mean =

distances, indexes = kn.Kneighbors([X_new])



